services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      # បន្ថែម args នៅទីនេះដើម្បីបញ្ជូនទិន្នន័យពេល Build
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      cache_from:
        - next-app:latest
    container_name: delivery-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # បងអាចទុកវានៅទីនេះមួយទៀតក៏បាន ដើម្បីសុវត្ថិភាព
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} 
    restart: unless-stopped